modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/TheIllusiveC4/CuriousElytra/issues"
logoFile="${mod_icon}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors="${mod_author}"
description='''
${mod_description}
'''
[[dependencies.curiouselytra]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouselytra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouselytra]]
    modId="caelus"
    mandatory=true
    versionRange="[0.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.curiouselytra]]
    modId="curios"
    mandatory=true
    versionRange="[0.10,)"
    ordering="NONE"
    side="BOTH"